### ISSUE TITLE
Causes Legacy mode on Paper servers

### ISSUE THREAD

**Issue by NIronwolf** [glguy/PdxExplorers#1]
Heya,

I know it's been like 10 years or so, but I wanted to say hi.  It's Ironwolf from back in the Minecraft days on PDXMC. Hope you've been well.

I'm still using your PDX Explorers plugin on my current server.  :)  It does complain a bit about being old.  I never got into writing mods for MC so I don't know how involved updating is.  It might just be adding something about the API version in the .yml but I honestly don't know.  Willing to take a look?

`[Server thread/WARN]: Legacy plugin PdxExplorers v1.11 does not specify an api-version.`

I think it causes Paper to also throw this error on the line above it in the log.

`[Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!`

Using Paper #388 (v1.18.2)

**Comment by glguy** [comment]
Oh wow! I'll take a look (but it might not be until this weekend). I've been out of the game for years :) I'll have to do some reading. Maybe it's an easy fix updating a manifest file.

**Comment by glguy** [comment]
@NIronwolf I think I updated the plugin and I tested it against your #388 and that seemed to work. I didn't change the data file format so it should be completely  compatible with your previous version

**Comment by NIronwolf** [comment]
@glguy I, um, don't know how to turn this into a .jar to work as a plugin.  I haven't really touched Java at all for almost 30 years.

**Comment by NIronwolf** [comment]
Installed Maven and got a build out of it.  No more warnings in the log. Looks like it's all working.  Thanks for taking the time to update!  Stop by sometime if you'd like.  mc.nironwolf.com
